// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type Secret struct {
	ID       int64          `json:"id"`
	Owner    sql.NullString `json:"owner"`
	Kind     sql.NullInt32  `json:"kind"`
	Name     sql.NullString `json:"name"`
	Value    []byte         `json:"value"`
	Created  sql.NullTime   `json:"created"`
	Modified sql.NullTime   `json:"modified"`
	Deleted  sql.NullBool   `json:"deleted"`
}

type User struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Passhash string `json:"passhash"`
}
