// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type Secret struct {
	ID       int64
	Owner    sql.NullString
	Kind     sql.NullInt32
	Name     sql.NullString
	Value    []byte
	Created  sql.NullTime
	Modified sql.NullTime
	Deleted  sql.NullBool
}

type User struct {
	ID       int32
	Name     string
	Passhash string
}
