// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CleanSecrets(ctx context.Context) ([]Secret, error)
	CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSecret(ctx context.Context, arg DeleteSecretParams) error
	DeleteUser(ctx context.Context, name string) error
	GetSecret(ctx context.Context, arg GetSecretParams) (Secret, error)
	GetSecretsByKind(ctx context.Context, arg GetSecretsByKindParams) ([]Secret, error)
	GetSecretsByUser(ctx context.Context, owner string) ([]Secret, error)
	GetUser(ctx context.Context, name string) (User, error)
	MarkSecretDeleted(ctx context.Context, arg MarkSecretDeletedParams) error
	UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error)
}

var _ Querier = (*Queries)(nil)
