// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: secrets.sql

package db

import (
	"context"
	"time"
)

const cleanSecrets = `-- name: CleanSecrets :many
DELETE FROM secrets
WHERE deleted = true
RETURNING id, owner, kind, name, value, created, modified, deleted
`

func (q *Queries) CleanSecrets(ctx context.Context) ([]Secret, error) {
	rows, err := q.db.QueryContext(ctx, cleanSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Secret
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Kind,
			&i.Name,
			&i.Value,
			&i.Created,
			&i.Modified,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSecret = `-- name: CreateSecret :one
INSERT INTO secrets (
  owner,
  kind,
  name,
  value,
  created,
  modified
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, owner, kind, name, value, created, modified, deleted
`

type CreateSecretParams struct {
	Owner    string
	Kind     int32
	Name     string
	Value    []byte
	Created  time.Time
	Modified time.Time
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, createSecret,
		arg.Owner,
		arg.Kind,
		arg.Name,
		arg.Value,
		arg.Created,
		arg.Modified,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Kind,
		&i.Name,
		&i.Value,
		&i.Created,
		&i.Modified,
		&i.Deleted,
	)
	return i, err
}

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secrets
WHERE owner = $1 AND kind = $2 AND name = $3
`

type DeleteSecretParams struct {
	Owner string
	Kind  int32
	Name  string
}

func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) error {
	_, err := q.db.ExecContext(ctx, deleteSecret, arg.Owner, arg.Kind, arg.Name)
	return err
}

const getSecret = `-- name: GetSecret :one
SELECT id, owner, kind, name, value, created, modified, deleted FROM secrets
WHERE owner = $1 AND kind = $2 AND name = $3
LIMIT 1
`

type GetSecretParams struct {
	Owner string
	Kind  int32
	Name  string
}

func (q *Queries) GetSecret(ctx context.Context, arg GetSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, getSecret, arg.Owner, arg.Kind, arg.Name)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Kind,
		&i.Name,
		&i.Value,
		&i.Created,
		&i.Modified,
		&i.Deleted,
	)
	return i, err
}

const getSecretsByKind = `-- name: GetSecretsByKind :many
SELECT id, owner, kind, name, value, created, modified, deleted FROM secrets
WHERE owner = $1 AND kind = $2
ORDER BY modified DESC
`

type GetSecretsByKindParams struct {
	Owner string
	Kind  int32
}

func (q *Queries) GetSecretsByKind(ctx context.Context, arg GetSecretsByKindParams) ([]Secret, error) {
	rows, err := q.db.QueryContext(ctx, getSecretsByKind, arg.Owner, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Secret
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Kind,
			&i.Name,
			&i.Value,
			&i.Created,
			&i.Modified,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSecretsByUser = `-- name: GetSecretsByUser :many
SELECT id, owner, kind, name, value, created, modified, deleted FROM secrets
WHERE owner = $1
ORDER BY modified DESC
`

func (q *Queries) GetSecretsByUser(ctx context.Context, owner string) ([]Secret, error) {
	rows, err := q.db.QueryContext(ctx, getSecretsByUser, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Secret
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Kind,
			&i.Name,
			&i.Value,
			&i.Created,
			&i.Modified,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSecretDeleted = `-- name: MarkSecretDeleted :exec
UPDATE secrets
SET deleted = true
WHERE owner = $1 AND kind = $2 AND name = $3
`

type MarkSecretDeletedParams struct {
	Owner string
	Kind  int32
	Name  string
}

func (q *Queries) MarkSecretDeleted(ctx context.Context, arg MarkSecretDeletedParams) error {
	_, err := q.db.ExecContext(ctx, markSecretDeleted, arg.Owner, arg.Kind, arg.Name)
	return err
}

const updateSecret = `-- name: UpdateSecret :one
UPDATE secrets
  set value = $4,
  created = $5,
  modified = $6
WHERE owner = $1 AND kind = $2 AND name = $3
RETURNING id, owner, kind, name, value, created, modified, deleted
`

type UpdateSecretParams struct {
	Owner    string
	Kind     int32
	Name     string
	Value    []byte
	Created  time.Time
	Modified time.Time
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, updateSecret,
		arg.Owner,
		arg.Kind,
		arg.Name,
		arg.Value,
		arg.Created,
		arg.Modified,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Kind,
		&i.Name,
		&i.Value,
		&i.Created,
		&i.Modified,
		&i.Deleted,
	)
	return i, err
}
