CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "passhash" varchar NOT NULL
);

CREATE TABLE "secrets" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner" varchar NOT NULL,
  "kind" int NOT NULL,
  "name" varchar NOT NULL,
  "value" bytea NOT NULL,
  "created" timestamptz DEFAULT (now()),
  "modified" timestamptz DEFAULT (now()),
  "deleted" boolean DEFAULT false
);
