CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "passhash" varchar NOT NULL
);

CREATE TABLE "secrets" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner" varchar NOT NULL,
  "kind" int NOT NULL,
  "name" varchar NOT NULL,
  "value" bytea NOT NULL,
  "created" timestamptz NOT NULL DEFAULT (now()),
  "modified" timestamptz NOT NULL DEFAULT (now()),
  "deleted" boolean NOT NULL DEFAULT false
);

