services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 5
  gophkeeper:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      GOPHKEEPER_DSN: postgresql://postgres:mysecretpassword@postgres:5432?sslmode=disable
      GOPHKEEPER_ADDRESS: "[::]:8080"
      GOPHKEEPER_ENV: dev
