services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  gophkeeper:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      GOPHKEEPER_DSN: postgresql://postgres:mysecretpassword@postgres:5432?sslmode=disable
      GOPHKEEPER_ADDRESS: "[::]:8080"
      GOPHKEEPER_ENV: dev
