name: build/test app

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.19
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Test
        run: make test
